# Generated by Django 3.2.9 on 2021-12-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('contact_reason', models.CharField(choices=[('general_query', 'General Query'), ('technical_issue', 'Technical Issue'), ('delivery', 'Delivery'), ('collection', 'Collection')], default='general_query', max_length=50)),
                ('message', models.TextField(max_length=1500)),
            ],
        ),
    ]
